In [ ]:
#importing the dataset
import pandas as pd
creditcard_data= pd.read_csv("/creditcard.csv")

In [ ]:
#first 5 rows of the dataset
creditcard_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
#dataset information
creditcard_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43681 entries, 0 to 43680
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    43681 non-null  int64
 1   V1      43681 non-null  float64
 2   V2      43681 non-null  float64
 3   V3      43681 non-null  float64
 4   V4      43681 non-null  float64
 5   V5      43681 non-null  float64
 6   V6      43681 non-null  float64
 7   V7      43681 non-null  float64
 8   V8      43681 non-null  float64
 9   V9      43681 non-null  float64
 10  V10     43681 non-null  float64
 11  V11     43681 non-null  float64
 12  V12     43681 non-null  float64
 13  V13     43681 non-null  float64
 14  V14     43681 non-null  float64
 15  V15     43681 non-null  float64
 16  V16     43681 non-null  float64
 17  V17     43681 non-null  float64
 18  V18     43680 non-null  float64
 19  V19     43680 non-null  float64
 20  V20     43680 non-null  float64
 21  V21     43680 non-null  float64
 22  V22     43680 non-null  float64
 23  V23     43680 non-null  float64
 24  V24     43680 non-null  float64
 25  V25     43680 non-null  float64
 26  V26     43680 non-null  float64
 27  V27     43680 non-null  float64
 28  V28     43680 non-null  float64
 29  Amount  43680 non-null  float64
 30  Class   43680 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 10.3 MB

In [ ]:
#checking the number of missing values in each column
creditcard_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of legit transaction & fraudlent transaction
creditcard_data['Class'].value_counts()

0.0    43546
1.0      134
Name: Class, dtype: int64

In [ ]:
#separating the data for analysis
legit=creditcard_data[creditcard_data.Class == 0]
fraud=creditcard_data[creditcard_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(43546, 31)
(134, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    43546.000000
mean        90.282096
std        238.422933
min          0.000000
25%          7.580000
50%         24.900000
75%         81.400000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     134.000000
mean       93.928433
std       231.551248
min         0.000000
25%         1.000000
50%         6.455000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
creditcard_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,26898.672025,-0.210226,0.014510,0.735489,0.173628,-0.226486,0.106833,-0.092822,0.03929,0.185006,...,0.046464,-0.029761,-0.109564,-0.039141,0.010125,0.135969,0.022214,0.004782,0.004930,90.282096
1.0,25259.246269,-7.759814,5.619386,-10.672832,6.111351,-5.776140,-2.360976,-8.192938,4.04000,-3.571525,...,0.507150,0.931331,-0.270332,-0.315606,-0.096976,0.279383,0.168436,0.687503,0.063472,93.928433

UNDER-SAMPLING

Build a sample dataset containing similar distributions of normal transaction and fraudlent transaction

No. of fraudlent transaction: 492

In [ ]:
legit_sample=legit.sample(n=492)

Concatinating two Dataframes

In [ ]:
new_dataset=pd.concat([legit_sample,fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
18212,29298,-0.235046,0.671208,0.497113,-0.302483,0.990454,0.229208,0.791992,-0.082866,-0.776206,...,0.007622,0.059707,-0.197540,-1.227011,-0.225461,1.192587,0.051861,0.112212,37.00,0.0
2496,2066,-0.767490,0.182111,1.736865,0.251423,-1.046391,-0.217258,-0.528523,0.625258,0.393029,...,0.076855,0.276781,0.320299,0.691233,-1.240529,0.870518,0.060173,0.091666,37.98,0.0
10229,15935,0.867881,-1.782953,1.969982,0.151113,-2.261607,1.168173,-1.975056,0.541426,2.218838,...,0.290976,1.116732,-0.242587,0.252688,0.286878,0.044799,0.054783,0.038244,169.00,0.0
20328,30959,1.217906,0.170565,-0.125731,0.952950,0.629836,0.931456,-0.016339,0.178420,0.020980,...,-0.131522,-0.137194,-0.251349,-1.315143,0.837360,-0.247621,0.038843,-0.006584,8.40,0.0
20667,31193,1.036875,-0.526274,1.210800,0.077064,-1.091146,0.232477,-0.783753,0.279826,0.747306,...,0.004472,0.130590,0.061019,0.313524,-0.019476,0.984282,-0.026205,0.012897,50.00,0.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    492
1.0    134
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,27030.097561,-0.137266,0.036883,0.723215,0.153990,-0.336819,0.151676,-0.106236,0.091827,0.214456,...,0.054699,-0.020653,-0.097821,-0.063903,0.040859,0.120130,0.071771,-0.004734,-0.005634,93.168984
1.0,25259.246269,-7.759814,5.619386,-10.672832,6.111351,-5.776140,-2.360976,-8.192938,4.040000,-3.571525,...,0.507150,0.931331,-0.270332,-0.315606,-0.096976,0.279383,0.168436,0.687503,0.063472,93.928433

In [ ]:
#splitting the data into features & targets
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

In [ ]:
print(X)

        Time         V1        V2         V3        V4         V5        V6  \
18212  29298  -0.235046  0.671208   0.497113 -0.302483   0.990454  0.229208
2496    2066  -0.767490  0.182111   1.736865  0.251423  -1.046391 -0.217258
10229  15935   0.867881 -1.782953   1.969982  0.151113  -2.261607  1.168173
20328  30959   1.217906  0.170565  -0.125731  0.952950   0.629836  0.931456
20667  31193   1.036875 -0.526274   1.210800  0.077064  -1.091146  0.232477
...      ...        ...       ...        ...       ...        ...       ...
43061  41353 -15.020981  8.075240 -16.298091  5.664820 -11.918153 -4.246957
43160  41397 -14.970346  8.401421 -16.867238  8.252334 -13.565130 -2.782438
43204  41413 -15.140450  7.378042 -16.356367  9.194935 -13.466163 -2.958431
43428  41505 -16.526507  8.584972 -18.649853  9.505594 -13.793819 -2.832404
43624  41582  -1.048005  1.300219  -0.180401  2.589843  -1.164794  0.031823

              V7         V8        V9  ...       V20       V21       V22  \
18212   0.791992  -0.082866 -0.776206  ...  0.280110  0.007622  0.059707
2496   -0.528523   0.625258  0.393029  ...  0.040748  0.076855  0.276781
10229  -1.975056   0.541426  2.218838  ...  0.224437  0.290976  1.116732
20328  -0.016339   0.178420  0.020980  ... -0.091809 -0.131522 -0.137194
20667  -0.783753   0.279826  0.747306  ...  0.019086  0.004472  0.130590
...          ...        ...       ...  ...       ...       ...       ...
43061 -14.716668   9.435084 -6.795398  ... -0.995787  2.525115 -0.832074
43160 -14.263735   9.643419 -7.701499  ... -1.614660  2.714045 -0.101355
43204 -16.165539  10.075254 -7.901821  ... -1.691482  3.147428  0.341678
43428 -16.701694   7.517344 -8.507059  ... -1.514923  1.190739 -1.127670
43624  -2.175778   0.699072 -1.140208  ...  0.644993  0.549014  0.624321

            V23       V24       V25       V26       V27       V28  Amount
18212 -0.197540 -1.227011 -0.225461  1.192587  0.051861  0.112212   37.00
2496   0.320299  0.691233 -1.240529  0.870518  0.060173  0.091666   37.98
10229 -0.242587  0.252688  0.286878  0.044799  0.054783  0.038244  169.00
20328 -0.251349 -1.315143  0.837360 -0.247621  0.038843 -0.006584    8.40
20667  0.061019  0.313524 -0.019476  0.984282 -0.026205  0.012897   50.00
...         ...       ...       ...       ...       ...       ...     ...
43061 -0.186117  0.429781  0.697103  0.056031 -1.310888 -0.707403   34.12
43160 -0.439666  0.519514  0.789328  0.064357 -1.621386 -1.104819  273.01
43204 -1.150162  0.795190 -0.194542  0.145964 -2.458680 -1.189888  106.55
43428 -2.358579  0.673461 -1.413700 -0.462762 -2.018575 -1.042804  364.19
43624 -0.136663  0.131738  0.030921 -0.176701  0.504898  0.069882   39.45

[626 rows x 30 columns]

In [ ]:
print(Y)

18212    0.0
2496     0.0
10229    0.0
20328    0.0
20667    0.0
        ...
43061    1.0
43160    1.0
43204    1.0
43428    1.0
43624    1.0
Name: Class, Length: 626, dtype: float64

In [ ]:
#Train test split
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(500, 30) (126, 30) (500,) (126,)

In [ ]:
#Model Training
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression(max_iter=5000)

In [ ]:
#Training the Logistic Regression Model with training data
model.fit(X_train,Y_train)

LogisticRegression(max_iter=5000)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
#Model Evaluation
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
print("Accuracy on Training Data:",training_data_accuracy)

Accuracy on Training Data: 0.994

In [ ]:
#accuracy on test data
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction, Y_test)

In [ ]:
print("Accuracy score on Test Data:",test_data_accuracy)

Accuracy score on Test Data: 0.9761904761904762